# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestuserregistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuserregistration(self):
    # Test name: test_user_registration
    # Step # | name | target | value
    # 1 | open | /ru/ | 
    self.driver.get("http://selenium1py.pythonanywhere.com/ru/")
    # 2 | setWindowSize | 1920x1053 | 
    self.driver.set_window_size(1920, 1053)
    # 3 | click | id=login_link | 
    self.driver.find_element(By.ID, "login_link").click()
    # 4 | click | id=id_registration-email | 
    self.driver.find_element(By.ID, "id_registration-email").click()
    # 5 | type | id=id_registration-email | test878@test.test
    self.driver.find_element(By.ID, "id_registration-email").send_keys("test878@test.test")
    # 6 | click | id=id_registration-password1 | 
    self.driver.find_element(By.ID, "id_registration-password1").click()
    # 7 | type | id=id_registration-password1 | 18273645N
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("18273645N")
    # 8 | click | id=id_registration-password2 | 
    self.driver.find_element(By.ID, "id_registration-password2").click()
    # 9 | type | id=id_registration-password2 | 18273645N
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("18273645N")
    # 10 | click | name=registration_submit | 
    self.driver.find_element(By.NAME, "registration_submit").click()
    # 11 | assertText | css=.alertinner | Спасибо за регистрацию!
    assert self.driver.find_element(By.CSS_SELECTOR, ".alertinner").text == "Спасибо за регистрацию!"
  
